beaker-endothermic:
 title: Beaker Endothermic
 filename: beaker-endothermic
 source: LaTeX Source
 extension: tex
 caption: Energy flow for an endothermic process taking place in a system inside a container with diathermal walls. 
 