solid-separated-in-beaker:
 title: Solid Separated in Beaker
 filename: solid-separated-in-beaker
 source: Adobe Illustrator Source
 extension: ai
 caption: Solid solute particles separated in a beaker.
 