sol-energetics-exothermic:
 title: Enthalpy Diagram for Exothermic Solution Formation
 filename: sol-energetics-exothermic
 source: LaTeX Source
 extension: tex
 caption: Enthalpy diagram showing the enthalpy changes associated with exothermic solution formation. 
 