solution-in-beaker:
 title: Solution in a Beaker
 filename: solution-in-beaker
 source: Adobe Illustrator Source
 extension: ai
 caption: Solute (gray circles) and solvent particles (blue circles) uniformaly distributed in a beaker to represent a solution.
 